/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTranslateRouteImport } from './routes/api/public/translate'
import { Route as ApiPublicStatsRouteImport } from './routes/api/public/stats'

const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTranslateRoute = ApiPublicTranslateRouteImport.update({
  id: '/api/public/translate',
  path: '/api/public/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStatsRoute = ApiPublicStatsRouteImport.update({
  id: '/api/public/stats',
  path: '/api/public/stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api-docs': typeof ApiDocsRoute
  '/payment': typeof PaymentRoute
  '/redeem': typeof RedeemRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/api/public/translate': typeof ApiPublicTranslateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api-docs': typeof ApiDocsRoute
  '/payment': typeof PaymentRoute
  '/redeem': typeof RedeemRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/api/public/translate': typeof ApiPublicTranslateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api-docs': typeof ApiDocsRoute
  '/payment': typeof PaymentRoute
  '/redeem': typeof RedeemRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/api/public/translate': typeof ApiPublicTranslateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api-docs'
    | '/payment'
    | '/redeem'
    | '/api/public/stats'
    | '/api/public/translate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api-docs'
    | '/payment'
    | '/redeem'
    | '/api/public/stats'
    | '/api/public/translate'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api-docs'
    | '/payment'
    | '/redeem'
    | '/api/public/stats'
    | '/api/public/translate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiDocsRoute: typeof ApiDocsRoute
  PaymentRoute: typeof PaymentRoute
  RedeemRoute: typeof RedeemRoute
  ApiPublicStatsRoute: typeof ApiPublicStatsRoute
  ApiPublicTranslateRoute: typeof ApiPublicTranslateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/translate': {
      id: '/api/public/translate'
      path: '/api/public/translate'
      fullPath: '/api/public/translate'
      preLoaderRoute: typeof ApiPublicTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stats': {
      id: '/api/public/stats'
      path: '/api/public/stats'
      fullPath: '/api/public/stats'
      preLoaderRoute: typeof ApiPublicStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiDocsRoute: ApiDocsRoute,
  PaymentRoute: PaymentRoute,
  RedeemRoute: RedeemRoute,
  ApiPublicStatsRoute: ApiPublicStatsRoute,
  ApiPublicTranslateRoute: ApiPublicTranslateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
